language: groovy

jdk:
    - oraclejdk7

env:
    - GRAILS_VERSION=2.2.4

before_install:
    - mkdir ~/.grails
    - cd ~/.grails
    - bash -c '{ curl http://files.thehyve.net/caches/grails_${GRAILS_VERSION}_cache.tar.gz  | tar xzf -; } || true'
    - cd -
    - rm -rf ~/.gvm
    - curl -s get.gvmtool.net > ~/install_gvm.sh
    - chmod 775 ~/install_gvm.sh
    - ~/install_gvm.sh
    - echo "gvm_auto_answer=true" > ~/.gvm/etc/config
    - source ~/.gvm/bin/gvm-init.sh
    - gvm install grails $GRAILS_VERSION || true

script:
    - grails clean
    - grails upgrade --non-interactive
    - grails test-app --non-interactive --stacktrace

